version: '3'
services:
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    volumes:
      - ./:/var/project
    working_dir: /var/project
    entrypoint: ["/usr/local/bin/node"]

  npm:
    build:
      context: docker/node
      dockerfile: Dockerfile
    volumes:
      - ./:/var/project
    working_dir: /var/project
    entrypoint: ["/usr/local/bin/npm"]

  npx:
    build:
      context: docker/node
      dockerfile: Dockerfile
    volumes:
      - ./:/var/project
    working_dir: /var/project
    entrypoint: ["/usr/local/bin/npx"]

  ncu:
    build:
      context: docker/node
      dockerfile: Dockerfile
    volumes:
      - ./:/var/project
    working_dir: /var/project
    entrypoint: ["/usr/local/bin/ncu"]