name: Build

on:
  push:
  pull_request:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      AWS_KEY: ${{ secrets.AWS_KEY }}
      AWS_SECRET: ${{ secrets.AWS_SECRET }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - uses: actions/checkout@v1

      - name: Build the container
        run: |
          docker-compose --file docker-compose.test.yml build --force-rm --compress
          docker-compose --file docker-compose.test.yml up --no-start --force-recreate
          docker-compose ps

      - name: Run tests
        run: |
          docker-compose --file docker-compose.test.yml run --rm sut-php71
          docker-compose --file docker-compose.test.yml run --rm sut-php71-apache
          docker-compose --file docker-compose.test.yml run --rm sut-php71-fpm
          docker-compose --file docker-compose.test.yml run --rm sut-php72
          docker-compose --file docker-compose.test.yml run --rm sut-php72-apache
          docker-compose --file docker-compose.test.yml run --rm sut-php72-fpm
