name: Docker Hub Description Sync

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Hub README & description sync
      uses: meeDamian/sync-readme@v1.0.6
      with:
        user: ${{ secrets.DOCKERHUB_USERNAME }}
        pass: ${{ secrets.DOCKERHUB_PASSWORD }}
